### ISSUE TITLE
Create instant messaging GUI components

### ISSUE THREAD

**Issue by 2bigO** [assister-ai/assister#7]
* Options Box
* Conversation
* [Message Card](https://github.com/keyvan-m-sadeghi/assister/blob/assister-conception/rfcs/text/assister-conception/README.md#response)
* Command Hint
* Autocomplete Input Box
* Voice Button
* Send Button

These should go to [assister](https://github.com/assister-ai/assister)`/packages/agent`.

![Wireframe](https://user-images.githubusercontent.com/1758649/55401447-c8567580-551e-11e9-825b-70e6c1b7d695.png)

*Wireframe*

Technologies:

* React [Hooks](https://reactjs.org/docs/hooks-intro.html)
* Redux [v7-beta](https://github.com/reduxjs/react-redux/issues/1177#issuecomment-475911457)

**Comment by farhoud** [comment]
Hi
Why we don't consider other freamworks like vue?
@keyvan-m-sadeghi

**Comment by 2bigO** [comment]
@farhoud I personally really like Vue, the reason for choosing React for me is the timing. What I know is that Hooks are a paradigm that Assister Agent can greatly benefit from, in terms of code simplicity. Vue has [recently started on adopting hooks](https://css-tricks.com/what-hooks-mean-for-vue/), though I guess it'll take a while before [the implementation](https://github.com/yyx990803/vue-hooks) is feature complete.

**Comment by farhoud** [comment]
@keyvan.m.sadeghi I personaly feel the  spec and technology is to much for prototype and we have a deadline comming up. I think we make sample prototype and after we can desgin and think deeper and better

**Comment by farhoud** [comment]
and I think vue is much faster than react redux , or at least we leave redux for later

**Comment by 2bigO** [comment]
@farhoud I do understand that adding libraries such as `redux` might sound like overkill at this point, not being a frontend expert, I'm totally open to studying alternatives. Specifically, `useContext` and `useReducer` might do the job at the current scale of the Agent. As for `Vue` vs `React`, I still think we should go with`React` with `Hooks` for the time being.

**Comment by farhoud** [comment]
okey. so we only have mobile view?
no desktop?

**Comment by 2bigO** [comment]
@farhoud I hope we can accommodate both given the small scale of the GUI. Our first release would be for desktop though.

**Comment by mehdibalouchi** [comment]
where do suggestions in `AutoComplete Input Box` come from? aren't they a little confusing along side with `CommandHints`?

**Comment by farhoud** [comment]
for the sake of demo and shorting hands me and k1 decide we use vue as backup plan for now:
https://github.com/farhoud/sanaz

**Comment by 2bigO** [comment]
@mehdibalouchi the command hint and autocomplete indeed  have similar functionality, though they serve different purposes. `CommandHint` is the guess for a "complete" command adhering to the command syntax, it signals to the user the command that is going to be executed based on the current input, as well as showing alternatives.

`AutoComplete`'s function is next word suggestion, so it won't necessarily adhere to the command syntax. Its purpose is fewer keystrokes.

**Comment by 2bigO** [comment]
> for the sake of demo and shorting hands me and k1 decide we use vue as backup plan for now:
> https://github.com/farhoud/sanaz

Right, @farhoud will be implementing the Agent GUI in parallel with `Vue`, @mehdibalouchi and I will focus on `React`. @farhoud will work with us on the `React` version after the `Vue` version that serves only the demo purpose (unless `vue hooks` emerge by then, in which case we should compare the two approaches and decide).

**Comment by farhoud** [comment]
I think bot most replay to messages for better user experince

**Comment by 2bigO** [comment]
@farhoud if a `function` returns a value, the bot replies with the corresponding Message Card. If it's `void`, a tick indicates completion.

**Comment by farhoud** [comment]
@keyvan-m-sadeghi 
can you open up issue for gui senario?
I have some feed back after lot of format A1:A3 date with sanaz.
I think its humanely to start new conversation with hello and clean history.
and we can open up sidebar for full history or even in options.
do and undo don't feel like a chat and may confused with some application do and undo.
one more thing the tick think can be replace with nice response peaple dont like when they dont get an answer even when its done.
other problem is by desgin popup closed by browser when the focus change and its more suited for recording only I think sidebar is the sloution.  

every tab need its own session for messages?

what happend if a function fail ?

oh an other thing can u define assister agent interface for mocking?

**Comment by 2bigO** [comment]
Summary of offline discussions:

- `Web Components` is a must for this project
-  We'll create a general **"Assister Chat"** component which is then used by the Agent
- After further investigating [lighterhtml](https://github.com/WebReflection/lighterhtml) and [Haunted](https://github.com/matthewp/haunted), we decided to go with [Stencil](https://github.com/ionic-team/stencil)

The decision on Stencil boils down to maturity of it as well as the ability to re-use [ionic components](https://github.com/ionic-team/ionic), the latter could potentially reduce our development costs.
